# Generated by Django 6.0.6 on 2026-06-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Справочник номенклатуры'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': 'Заявка на закупку', 'verbose_name_plural': 'Заявки на закупку'},
        ),
        migrations.AlterModelOptions(
            name='requesthistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запись истории', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='requests_files/', verbose_name='Прикрепленный документ (счет, ТЗ)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchases.purchaserequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время изменения'),
        ),
    ]
